# Generated by Django 5.2.3 on 2025-06-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="tittle",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.TextField(help_text="Comma-separated skills"),
        ),
    ]
