# Generated by Django 5.2.3 on 2025-06-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_tittle_job_title_alter_job_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.RemoveField(
            model_name="job",
            name="skills",
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="required_skills",
            field=models.TextField(
                default="defualt", help_text="Comma separated skills"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="ResumeMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_file", models.FileField(upload_to="resumes/")),
                ("extracted_skills", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("matched_jobs", models.ManyToManyField(blank=True, to="app.job")),
            ],
        ),
    ]
