# Generated by Django 5.2.3 on 2025-06-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_job_company_remove_job_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="required_skills",
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.CharField(
                default="default", help_text="Comma-separated skills", max_length=500
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
